CREATE COLUMN TABLE NATION (
    N_NATIONKEY  INTEGER NOT NULL,
    N_NAME       CHAR(25),
    N_REGIONKEY  INTEGER,
    N_COMMENT    VARCHAR(152),
    PRIMARY KEY (N_NATIONKEY)
);

CREATE COLUMN TABLE REGION (
    R_REGIONKEY  INTEGER NOT NULL,
    R_NAME       CHAR(25),
    R_COMMENT    VARCHAR(152),
    PRIMARY KEY (R_REGIONKEY)
);

CREATE COLUMN TABLE PART (
    P_PARTKEY     INTEGER NOT NULL,
    P_NAME        VARCHAR(55),
    P_MFGR        CHAR(25),
    P_BRAND       CHAR(10),
    P_TYPE        VARCHAR(25),
    P_SIZE        INTEGER,
    P_CONTAINER   CHAR(10),
    P_RETAILPRICE DECIMAL(15,2),
    P_COMMENT     VARCHAR(23),
    PRIMARY KEY (P_PARTKEY)
);

CREATE COLUMN TABLE SUPPLIER (
    S_SUPPKEY     INTEGER NOT NULL,
    S_NAME        CHAR(25),
    S_ADDRESS     VARCHAR(40),
    S_NATIONKEY   INTEGER NOT NULL,
    S_PHONE       CHAR(15),
    S_ACCTBAL     DECIMAL(15,2),
    S_COMMENT     VARCHAR(101),
    PRIMARY KEY (S_SUPPKEY)
);

CREATE COLUMN TABLE PARTSUPP (
    PS_PARTKEY     INTEGER NOT NULL,
    PS_SUPPKEY     INTEGER NOT NULL,
    PS_AVAILQTY    INTEGER,
    PS_SUPPLYCOST  DECIMAL(15,2),
    PS_COMMENT     VARCHAR(199),
    PRIMARY KEY (PS_PARTKEY, PS_SUPPKEY)
);

CREATE COLUMN TABLE CUSTOMER (
    C_CUSTKEY     INTEGER NOT NULL,
    C_NAME        VARCHAR(25),
    C_ADDRESS     VARCHAR(40),
    C_NATIONKEY   INTEGER NOT NULL,
    C_PHONE       CHAR(15),
    C_ACCTBAL     DECIMAL(15,2),
    C_MKTSEGMENT  CHAR(10),
    C_COMMENT     VARCHAR(117),
    PRIMARY KEY (C_CUSTKEY)
);

CREATE COLUMN TABLE ORDERS (
    O_ORDERKEY       INTEGER NOT NULL,
    O_CUSTKEY        INTEGER NOT NULL,
    O_ORDERSTATUS    CHAR(1),
    O_TOTALPRICE     DECIMAL(15,2),
    O_ORDERDATE      DATE,
    O_ORDERPRIORITY  CHAR(15),
    O_CLERK          CHAR(15),
    O_SHIPPRIORITY   INTEGER,
    O_COMMENT        VARCHAR(79),
    PRIMARY KEY (O_ORDERKEY)
)
PARTITION BY RANGE (O_ORDERDATE) (
    PARTITION '1992-01-01' <= VALUES < '1993-01-01',
    PARTITION '1993-01-01' <= VALUES < '1993-05-30',
    PARTITION '1993-05-30' <= VALUES < '1994-05-27',
    PARTITION '1994-05-27' <= VALUES < '1995-01-02',
    PARTITION '1995-01-02' <= VALUES < '1997-05-01',
    PARTITION '1997-05-01' <= VALUES < '1997-09-02',
    PARTITION OTHERS
);

CREATE COLUMN TABLE LINEITEM (
    L_ORDERKEY    INTEGER NOT NULL,
    L_PARTKEY     INTEGER NOT NULL,
    L_SUPPKEY     INTEGER NOT NULL,
    L_LINENUMBER  INTEGER,
    L_QUANTITY    DECIMAL(15,2),
    L_EXTENDEDPRICE  DECIMAL(15,2),
    L_DISCOUNT    DECIMAL(15,2),
    L_TAX         DECIMAL(15,2),
    L_RETURNFLAG  CHAR(1),
    L_LINESTATUS  CHAR(1),
    L_SHIPDATE    DATE,
    L_COMMITDATE  DATE,
    L_RECEIPTDATE DATE,
    L_SHIPINSTRUCT CHAR(25),
    L_SHIPMODE     CHAR(10),
    L_COMMENT      VARCHAR(44),
    PRIMARY KEY (L_ORDERKEY, L_LINENUMBER)
)
PARTITION BY RANGE (L_SHIPDATE) (
    PARTITION '1992-01-02' <= VALUES < '1993-01-01',
    PARTITION '1993-01-01' <= VALUES < '1994-01-01',
    PARTITION '1994-01-01' <= VALUES < '1995-01-01',
    PARTITION '1995-01-01' <= VALUES < '1996-05-21',
    PARTITION OTHERS
);
